### ISSUE TITLE
Can't get audio and sensors working together

### ISSUE THREAD

**Issue by florianharmel** [zakaton/Bose-Frames-Web-SDK#2]
Hello,
The SDK is working perfectly when it comes to get informations about sensors and gestures but I am struggling at finding a way to have the sound in the same time.
To get it work, I need to disconnect from my Mac the frames then to pair them with the app and I have a LE-* device connected not recognised as audio.
Any idea?

**Comment by zakaton** [comment]
Hey Florian,

Unfortunately you have to connect to the Frames twice; once as an audio headset, and another as an AR headset, decoupling the audio and sensor/gesture data. The SDK connects to the AR headset component, but you have to connect to the Frames as an audio headset the conventional way (going to the bluetooth settings on whatever native platform you're using and connecting there)

One can see this as an annoyance, but another can see this as an opportunity. For instance you can connect to multiple Frames devices for a local multiplayer game. Another instance is you can play the audio on another headset and use the Frames just for grabbing head articulation data (imagine one person wearing the Frames but the spatialized audio is playing on someone else's headphones - wouldn't that be something?)

In either case, sorry about the inconvenience. I can't wait to see what you make with them!

-Zack
